<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="turbo.jpg" />
    <None Remove="voice.wav" />
    <None Remove="WhatsApp Audio 2026-03-16 at 15.28.10.wav" />
    <None Remove="WhatsApp Image 2026-05-28 at 15.56.29.jpeg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="turbo.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Content Include="voice.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="WhatsApp Audio 2026-03-16 at 15.28.10.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="WhatsApp Image 2026-05-28 at 15.56.29.jpeg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
